name: "Terraform-Plan-Infra-Plan"

on:
  workflow_dispatch:
  push:
    branches:
      - FeatureBranch1

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: AKIA3YCGH7KTGTFIAPP3
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: 'ap-south-1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        #with:
          #cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
